#!/bin/python3

import math
import os
import random
import re
import sys



def arrayManipulation(n, queries):
    nums = [0] * (n+2)
    for start, end, summand in queries:
        nums[start] += summand
        nums[end+1] -= summand
    nums.pop()
        
    r_sum = 0
    res = 0
    
    for num in nums:
        r_sum += num
        res = max(res, r_sum)
        
    return res
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    queries = []

    for _ in range(m):
        queries.append(list(map(int, input().rstrip().split())))

    result = arrayManipulation(n, queries)

    fptr.write(str(result) + '\n')

    fptr.close()
